### ISSUE TITLE
Add #[bench]s for algo::dominators

### ISSUE THREAD

**Issue by fitzgen** [bluss/petgraph#108]
Would be useful to have benches for different size graphs, maybe 1k, 10k, and 100k nodes? Would be interesting to compare with LT once it's implemented (#107) since the simple/fast paper found that their implementation was faster than LT until the flow graph had around 30k nodes.

**Comment by bluss** [comment]
This is welcome as a PR, but we won't track it as an open issue!

No disrespect to open enhancements, but we have open issues for much simpler things (adding basic graph trait impls etc), so it's not much point in keeping loose strings around when none are being consumed at all.
