### ISSUE TITLE
`GraphRef` without `Copy`

### ISSUE THREAD

**Issue by emallson** [bluss/petgraph#112]
The critical trait `GraphRef` requires `Copy`, which isn't always possible to implement. 

In my case, I have an mmap-backed graph that I'd wrapped in `Graphlike` as of 0.2. I've been trying to update it to 0.4.1 but haven't found a good solution to this, since an mmap can't safely implement `Copy` (any modifications would modify the underlying file, violating the semantics of `Copy`).

From what I can tell, the `Copy` trait constraint is necessary because of the `detach()` functions, but I'm not sure (the implicitness of `Copy` makes it somewhat difficult to tell without getting in-depth with the code). 

Is it possible to drop the `Copy` constraint from `GraphRef`? With a bit of guidance I can take a shot at implementing it and submit a PR.

(this isn't exactly blocking for me, as right now I'm just going to load things into memory. However, I have a few datasets that are large enough that being able to mmap them to trade speed for memory is useful.)

**Comment by bluss** [comment]
it's intended to be a reference (or something similar, like `Reversed(&G)`). Is that not possible? Shared references are Copy. The graph traversal traits are heavily restricted due to the limitations of traits + iterators + lifetimes, and we use the ideas of IntoIterator (think IntoIterator for `&[T]`).

**Comment by bluss** [comment]
For example, see exactly which types IntoNeighbors is implemented for https://docs.rs/petgraph/0.4.1/petgraph/visit/trait.IntoNeighbors.html

**Comment by emallson** [comment]
Oh! That makes sense. I have implemented for `&'a T` instead of `T` and all appears well. Thank you!
