### ISSUE TITLE
Mutable access to the underlying edge/node arrays

### ISSUE THREAD

**Issue by fuine** [bluss/petgraph#117]
In my application i have several places in which i need to separately mutate weigth of each edge in the graph. currently i do this in the following manner:
```
for edge in graph.edge_weights_mut() {
    // do something in here
}
```
I understand the design decision to not to introduce parallelization in `petgraph`, but this `for` loop is one of the hottest in my application and the entire problem is embarassingly parallel. I think that if i had something like `raw_edges` but for `&mut [Edge<E, Ix>]` i could just plug `par_iter_mut` and hopefully it should yield a significant speed up on a multicore machine. This way `petgraph` can abstract from the parallelization, but users can opt-in to use it outside of the crate if they see fit.

Do you think that adding `raw_edges_mut` and/or `raw_nodes_mut` is viable? As always i'm willing to implement it if you happen to accept this proposition.

**Comment by bluss** [comment]
Sure, it makes total sense. We want to enable outside extensions of `Graph`. I'm not quite sure where to place these encapsulation-busting methods (I think the existing raw_edges etc are already that). My suggestion would be to have such methods in a trait. `trait GraphInternal` for example.

**Comment by bluss** [comment]
Note: Some existing methods may belong in GraphInternal, but we'll start with only new methods there.

**Comment by fuine** [comment]
So to be clear on that, do you want to only include `raw_edges_mut` and `raw_nodes_mut` in the new trait, or do you want non-mutable versions as well?

**Comment by bluss** [comment]
I suppose the non-mut methods can be on the trait too. With the same signature as the inherent methods.

**Comment by bluss** [comment]
This is basically postponed, maybe we won't want to expose these (at least not for StableGraph)
