### ISSUE TITLE
IntoNodeReferences not implemented for StableGraph

### ISSUE THREAD

**Issue by generalelectrix** [bluss/petgraph#122]
Is there some reason that StableGraph does not implement IntoNodeReferences?

**Comment by bluss** [comment]
The only reason I can see is that according to the docs:

> Depends on crate feature stable_graph (default). This is a new feature in petgraph. You can contribute to help it achieve parity with Graph.

**Comment by generalelectrix** [comment]
Cool!  I may try my hand at that imp and submit a PR.

**Comment by bluss** [comment]
Fixed with IntoNodeReferences for &StableGraph in 75ad60e8e3019e3da32c4102cd621edfbda50c20 (petgraph 0.4.6)
