### ISSUE TITLE
Mutable equivalent to `AllEdges`

### ISSUE THREAD

**Issue by Binero** [bluss/petgraph#128]
I am not sure how to get an iterator with mutable access to all edge weights in a `GraphMap`. Is this even possible?

**Comment by Binero** [comment]
It seems like a good substitute is using `all_edges` together with `edge_weight_mut`?

**Comment by bluss** [comment]
It is indeed missing. That combination will not pass the borrow checker unfortunately.

**Comment by Binero** [comment]
Yeah, I just realised.
