### ISSUE TITLE
GraphMap Edge Reference

### ISSUE THREAD

**Issue by Binero** [bluss/petgraph#131]
Is there a way in `GraphMap` to get a reference to an edge? I cannot seem to find one.

**Comment by bluss** [comment]
An edge is identified by `(N, N)`, so that's the extent of it.

**Comment by Binero** [comment]
Yes, but there doesn't seem to be an interface exposing a reference of an edge. I'm looking for the edge itself, and how to get it when I have (N, N).

**Comment by bluss** [comment]
Do you mean the edge weight? There's nothing more than (N, N) and the edge weights.

**Comment by Binero** [comment]
Yes, the edge weight.

**Comment by bluss** [comment]
`.edge_weight{,_mut}(a, b)` methods or indexing with `graph[(a, b)]` should work for that.a

**Comment by Binero** [comment]
Oh wow, entirely my bad. Not sure how I overlooked that.
