### ISSUE TITLE
"algo::bellman_ford" gives me negative cycle errors although there is only a negative noncyclic graph

### ISSUE THREAD

**Issue by heartsh** [bluss/petgraph#135]
I'm writing software to build a rooted (directed) tree from an unrooted (undirected) tree using Petgraph.
To identify a path with a maximum length, first convert a positive undirected graph to negative one.
Then process it with the "bellman_ford", but it gives me the above errors.
Checked the structure of the negative one, but it seems not to have any cyclic path. (Tried with a small set of leaves (25 ones) for debugging.)
The tree correctly has 25 leaves, 23 internal nodes, and 47 edges. (If it were converted to a rooted one, the rooted one correctly does 25 leaves, 24 internal nodes, and 49 edges by adding 1 node and 2 edges.)

**Comment by bluss** [comment]
Hi, I'm sure this is easily fixed once we have a reproducing example.

**Comment by heartsh** [comment]
Thank you for your quick reply.
I noticed the algorithm be for only "directed" graph, apparently it's my mistake.
If its function required "directed" edge type for any graph (e.g., using trait), inappropriate use of the function would be blocked.

**Comment by bluss** [comment]
FWIW, I added a quickcheck for testing a random graph of positive weights. That's a too simple to show the error.

**Comment by bluss** [comment]
I wasn't sure the algo should be restricted to only directed graphs. Wikipedia thinks so, though.

**Comment by heartsh** [comment]
I meant the Bellman-Ford algorithm be for only "directed" one while the Dijkstra algorithm be for both.

**Comment by heartsh** [comment]
Understood.
I'm gonna use the Dijkstra algo. with inverted positive weights, instead.
Thank you.
