### ISSUE TITLE
IntoNodeIdentifiers/References is bounded on immutable refs in NodeFiltered

### ISSUE THREAD

**Issue by bright-star** [bluss/petgraph#137]
https://docs.rs/petgraph/0.4.4/petgraph/visit/struct.NodeFiltered.html

For example, the following fails if `tree: &mut StableGraph<_, usize>`, but works if `tree: &StableGraph<_, usize>`:

```rs
let end_index = EdgeIndex::<u32>::end();

let dead_leaf_inds: Vec<_> = NodeFiltered::from_fn(tree, |node_ind| {
    tree.edges_directed(node_ind, Outgoing)
        .any(|edge_ref| edge_ref.id() == end_index)
  }).node_identifiers().collect();
```

Error:

```
no method named `node_identifiers` found for type `petgraph::visit::NodeFiltered<&mut petgraph::prelude::StableGraph<_, usize>, [closure@viterbi.rs:265:52: 268:4 tree:_, end_index:_]>` in the current scope
the method `node_identifiers` exists but the following trait bounds were not satisfied: `petgraph::visit::NodeFiltered<&mut petgraph::prelude::StableGraph<_, usize>, [closure@viterbi.rs:265:52: 268:4 tree:_, end_index:_]> : petgraph::visit::IntoNodeIdentifiers`, `&mut petgraph::prelude::StableGraph<_, usize> : petgraph::visit::IntoNodeIdentifiers`
```

Is there any reason why the tree ref needs to be immutable here?

**Comment by bluss** [comment]
It's similar to `IntoIterator`, to get an `std::slice::Iter` you have to input `&[T]`. Isn't it simple to put in `&*tree` to make it a shared reference?

Now the IntoIterator formulation of all this is not ideal, but I think it's what we have until something like the ATC Rfc comes to Rust.

**Comment by bluss** [comment]
By the way, .edges() is the outgoing edges iterator too.

**Comment by bright-star** [comment]
Sorry, "put in `&*tree`" where?

**Comment by bluss** [comment]
Where you have `NodeFiltered::from_fn(tree` you can try `NodeFiltered::from_fn(&*tree`

**Comment by bright-star** [comment]
Doesn't seem to cut it:
```rs
let dead_leaf_inds: Vec<_> = NodeFiltered::from_fn(&*tree, |node_ind| {
    tree.edges_directed(node_ind, Outgoing)
        .any(|edge_ref| edge_ref.id() == end_index)
  }).node_references().collect();
```

```
the method `node_references` exists but the following trait bounds were not satisfied: `petgraph::visit::NodeFiltered<&petgraph::prelude::StableGraph<_, usize>, [closure@viterbi.rs:265:62: 268:4 tree:_, end_index:_]> : petgraph::visit::IntoNodeReferences`, `&petgraph::prelude::StableGraph<_, usize> : petgraph::visit::IntoNodeReferences`

no method named `node_references` found for type `petgraph::visit::NodeFiltered<&petgraph::prelude::StableGraph<_, usize>, [closure@viterbi.rs:265:62: 268:4 tree:_, end_index:_]>` in the current scope
```

**Comment by bluss** [comment]
Ok, thanks for the detailed message. In this case it's because &StableGraph does not implement IntoNodeReferences yet.

**Comment by bright-star** [comment]
Ah, got it. That helps, thanks.

**Comment by bright-star** [comment]
If I make a probably crappy impl and submit a PR, will you give it love?

**Comment by bluss** [comment]
A PR would not implement it for a mutable ref, but for a shared reference, just like the other impls.

**Comment by bright-star** [comment]
Got it. Sorry, I was distracted by some things I was trying in the visit module.

I think this is close, but I'm having trouble understanding how to line up the Option type declaration:

### stable_graph.rs

```rust
impl<'a, N, E, Ty, Ix> IntoNodeReferences for &'a StableGraph<N, E, Ty, Ix>
    where Ty: EdgeType,
          Ix: IndexType,
{
    type NodeRef = (NodeIndex<Ix>, &'a N);
    type NodeReferences = NodeReferences<'a, Option<N>, Ix>;
    fn node_references(self) -> Self::NodeReferences {
        NodeReferences {
            iter: self.g.nodes.iter().enumerate()
        }
    }
}
```

Error:

```
found type `(graph_impl::NodeIndex<Ix>, &N)` [E0271]

expected type `(graph_impl::NodeIndex<Ix>, &std::option::Option<N>)` [E0271]
```

Out of all of the permutations of adding or not adding `Option<>` around the `N` node types in the `impl` block, I haven't been able to get any to clear this error.

**Comment by bluss** [comment]
Ok great, thanks for looking into this! I think it wasn't covered yet since it involves some repetitive code generation and I had already implemented so many graph traits. StableGraph should get there in the end.

The idea must be of course that it only produces the actual existing nodes, so we handle the Nones in the underlying graph by skipping them in StableGraph's iterator.

We'll need to create a new iterator for this.  It can then produce the same item, the `(NodeIndex, &N)` tuple.

So StableGraph needs its own version of this: https://docs.rs/petgraph/0.4.4/src/petgraph/graph.rs.html#1869-1888

It needs to skip the None'd out nodes, and thus the size hint is not exact like it is for Graph's version.

**Comment by bluss** [comment]
Fixed with IntoNodeReferences for &StableGraph in 75ad60e8e3019e3da32c4102cd621edfbda50c20
