### ISSUE TITLE
Can't create a graphmap with String node identifiers

### ISSUE THREAD

**Issue by Zteve** [bluss/petgraph#145]
The unit tests for `graphmap` appear to use `&str` or integral types for the node identifier type.

In my own application it is most useful to have `String` or similar for the node identifiers which are discovered (with file input) at run time.

Unfortunately, `String` does not implement the `NodeTrait` trait (which equals `Copy + Ord + Hash`).  Why is `NodeTrait` so restrictive?  Wouldn't `Clone + Ord + Hash` be sufficient (with some minor adjustments in the code)? Is there some simple answer to this which I don't know?

I've tried making a tweak to `NodeTrait` in a clone of the repo, but I am not experienced enough to track down all the breakages and fix them.

[Pardon me for putting this question here as an issue, but it is not apparent where general questions like this should go.]

**Comment by bluss** [comment]
To be clear, this is by design. it's how GraphMap is, so it's not a bug. Sure, it would be neat to implement data structures with other features.
