### ISSUE TITLE
Warning 0122

### ISSUE THREAD

**Issue by Bromind** [bluss/petgraph#148]
On version 1.16 (not tried with 1.17), compiling petgraph generates a warning 0122 : 

== MWE ==
```
$ cd /path/to/petgraph/folder
$ cargo build
   Compiling fixedbitset v0.1.6
   Compiling ordermap v0.2.10
   Compiling petgraph v0.4.4 (file:///tmp/petgraph-master)
warning[E0122]: trait bounds are not (yet) enforced in type definitions
   --> src/algo/mod.rs:169:1
    |
169 | type DfsSpaceType<G> where G: Visitable = DfsSpace<G::NodeId, G::Map>;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

    Finished dev [unoptimized + debuginfo] target(s) in 2.97 secs
```

Maybe just wait and see with future versions of rust ? Anyway, I push the issue just to keep track of it.

Best, 

Bromind

**Comment by bluss** [comment]
Thanks for pinging with an issue. The thing with this warning and lacking feature is age-old. I'd prefer to not keep an issue for this. Trivial stuff should be fixed on sight instead.

**Comment by Arnavion** [comment]
I didn't think it would, but `type DfsSpaceType<G> = DfsSpace<<G as Visitable>::NodeId, <G as Visitable>::Map>;` [*does* compile,](http://play.integer32.com/?gist=a7fcfa7e1300ee1b4e13126143029e4c&version=stable) doesn't have the warning, and seems to have the expected result - `DfsSpaceType<Foo>` compiles only if `Foo` impls `Visitable` and errors otherwise.

**Comment by Arnavion** [comment]
(Fixed by 2ee6b973ae3fff564e282afe23e207385597d6e7 )

**Comment by bluss** [comment]
@Arnavion indeed. It looks wrong but as long as we are not hit with new rustc breaking changes over that it's good.

**Comment by bluss** [comment]
I'm tempted to revert this fix and go back to the warning code. Compare the docs:

- 0.4.5 https://docs.rs/petgraph/0.4.5/petgraph/algo/fn.toposort.html
- 0.4.6 https://docs.rs/petgraph/0.4.6/petgraph/algo/fn.toposort.html

The 0.4.6 version is visually offensive
