### ISSUE TITLE
More examples?

### ISSUE THREAD

**Issue by m4b** [bluss/petgraph#174]
Some more examples would be helpful, especially on how to use certain iterators, e.g.: https://docs.rs/petgraph/0.4.9/petgraph/graph/struct.Graph.html#method.node_indices

would be nice to show stuff like.

```rust
        for id in cfg.node_indices() {
            if let Some(&thing) = cfg.node_weight(id) {

```

**Comment by jmcomets** [comment]
I'm closing this in favor of #258 (dupe). I'll include your note on iterators there.
