### ISSUE TITLE
Friendlier direct node iteration

### ISSUE THREAD

**Issue by m4b** [bluss/petgraph#175]
Perhaps I'm using it wrong or couldn't find the idiomatic way to iterate nodes directly (I see there's a mutable version, `node_weights_mut` but perhaps an oversight there's no `node_weights` iterator?), but I really dislike this pattern:

```rust
for id in cfg.node_indices() {
   if let Some(&thing) = cfg.node_weight(id) {
```

In panopticon's graph algos I explicitly added direct mutable/immutale label/weight iterators because that pattern is so common and so unpleasant (imho).

E.g.:

```rust
pub type VertexLabelIterator<'a, K, V> = std::collections::hash_map::Values<'a, K, V>;
pub type VertexLabelMutIterator<'a, K, V> = std::collections::hash_map::ValuesMut<'a, K, V>;

impl<'a, V: 'a, E> VertexListGraph<'a, V, E> for AdjacencyList<V, E> {
    type Vertices = std::iter::Map<std::collections::hash_map::Keys<'a, Self::Vertex, V>, fn(&Self::Vertex) -> Self::Vertex>;
    type VertexLabels = std::collections::hash_map::Values<'a, Self::Vertex, V>;

    fn num_vertices(&self) -> usize {
        return self.vertex_labels.len();
    }

    fn vertices(&'a self) -> Self::Vertices {
        return self.vertex_labels.keys().map(std::clone::Clone::clone);
    }

    fn vertex_labels(&'a self) -> Self::VertexLabels {
        self.vertex_labels.values()
    }
}
```

This was easier since it just used hashmaps as backings and I could typedef their iterators, and then reexport them (since they themselves were then used in further iterator definitions).

I don't know how it would work for your library (haven't looked at internals), but I'm hoping can get both node_weight and edge_weight non-mut iterators.

**Comment by bluss** [comment]
Yes I have missed them too. It would be good to add.

**Comment by bluss** [comment]
Oh, friendlier node iteration already exists, it's hidden away in the [IntoNodeReferences](https://docs.rs/petgraph/0.4.10/petgraph/visit/trait.IntoNodeReferences.html#tymethod.node_references) graph trait.

Import the trait, and graph has the `node_references` method which yields the iterator element `(NodeIndex, &N)`

**Comment by m4b** [comment]
I see. I wonder if it will be good to have a trait/graph native method chart to illustrate the api surface/differences?

**Comment by bluss** [comment]
A table sounds great, or any other illustration we can think of (anything that renders in rustdoc is easier to publish, but we use illustrations already, so that's fine too.)

Maybe to be really fun we'd make a `dot` illustration of the methods, but that's probably a lot more work for the same reward :smile:

I think we can close this, since .node_references() -> Iterator<Item=(NodeIndex, &NodeWeight) exists?

**Comment by m4b** [comment]
Yes definitely can close. :+1:

**Comment by fiws** [comment]
Super rust noob here. I also had the same problem. 

Maybe I'm wrong, but isn't this a very basic operation/use case. I had to research this for half an hour.
Is there a reason why graphs don't simply have a `nodes_iter()` method or something like that?

**Comment by bluss** [comment]
@fiws Please use https://docs.rs/petgraph/0.4.12/petgraph/visit/trait.IntoNodeReferences.html and report new issues if there are bugs

**Comment by fiws** [comment]
I got that, I was just pointing out my ergonomic issue here.

Is there a reason why a feature like this is hidden in some trait without documentation?
Is the usecase uncommon? Or do most people know to search for a trait like that?

**Comment by bluss** [comment]
@fiws It would be cool if you could contribute the doc improvements that you imagine. There's no better person for this than you, that knows what was hard to find.  The answer in an open source project is always that nobody got around to making it better.
