### ISSUE TITLE
Dominator frontiers

### ISSUE THREAD

**Issue by m4b** [bluss/petgraph#176]
I attempted to implement dominance frontiers because I need it, but couldn't figure out how to

I'm also really not good at graph algos so yea, that was also depressing.

But iiuc I believe I'll need `edges_directed(n, Direction::Incoming)` to access the predecessors; unfortunately I don't see a trait providing that method in `visitors` (I think this is the place to look).

If I'm correct in all this, does this mean `dominators.rs` can't currently implement dominance frontiers as is, without further work in visitors, etc.?

I'm probably just missing something.  Hopefully.

**Comment by bluss** [comment]
Hey, you're right! IntoEdgesDirected is a missing trait. I'll see about adding it. It's issue #125
