### ISSUE TITLE
Graphs should impl `IntoIter`

### ISSUE THREAD

**Issue by m4b** [bluss/petgraph#180]
This would allow a client to iterate the petgraph without explicitly depending on petgraph as a dependency or providing the necessary import magic, etc.

**Comment by bluss** [comment]
Needs more details. What iterator element type do you expect? Equivalent to any current iterator?

**Comment by m4b** [comment]
I guess I'd expect it to behave like `node_references`; then again why not iterate edges.

Perhaps it could return a `(node_weight, edge_neighbor_iterator)` that way could iterate the whole graph.

dunno this is probably half-baked ;)
