### ISSUE TITLE
Edges().Cloned() still implies a borrow?

### ISSUE THREAD

**Issue by bnbowman** [bluss/petgraph#193]
I’m trying to search through a graph for a particular element, then either update it’s value (if it exists) or add it (if it doesn’t). But the Rust compiler tells me that I can’t because the call to the initial iterator (“edges()”) is an immutable borrow of the graph object, so I can’t mutate it later - fair enough.

After search around online, I see that the general solution is to clone() or cloned() the iterator, and the function is implemented for Edges(), but that’s not working for me. What am I missing here?

```
let out_edge = graph.edges(prev_node)
                                 .cloned()
                                 .find( |&e| function_body_here );
match out_edge {
    Some(e) => {
        *self.graph.edge_weight_mut(e.id()).unwrap() += 1;
    }
    None    => {
        let new_node = self.graph.add_node(xchar);
        self.graph.add_edge(prev_node, new_node, 1);
        prev_node = new_node;
    }
}
```

**Comment by bluss** [comment]
Yes, that doesn't change the borrowing. Pick clone or cloned and bring the question to Rust's IRC, and it can be explained there.
