### ISSUE TITLE
`algo::bellman_ford` should return the `source` and `target` indices when returning the `NegativeCycle` error.

### ISSUE THREAD

**Issue by mitchmindtree** [bluss/petgraph#195]
This can be useful when using `bellman_ford` to find negative cycles (e.g. in exchange arbitrage).

**Comment by bluss** [comment]
:smile: That's a fun idea, but I will actually close this. We don't need all loose ideas as issues. If this is an actual use case that you are pursuing, make sure to say so in the issue (and it will not be closed).

As always, I hope that algorithms can be built upon petgraph and just not in petgraph.
