### ISSUE TITLE
(Stable)Graph are not PartialEq

### ISSUE THREAD

**Issue by sanmai-NL** [bluss/petgraph#199]
Because `Node` and `Edge` are not `PartialEq`, it is not possible to compare graphs straightforwardly, as far as I know. I assume common traits aren’t implemented for `Node` and `Edge` because it would limit the genericity of the weight types (related, @bluss in https://github.com/bluss/petgraph/issues/37#issuecomment-250997896). What would be required (e.g., Rust features, code in this crate, library user code, etc.) to support `PartialEq` (Stable)Graph values?

**Comment by bluss** [comment]
Can you describe what the equivalence criteria are for two graphs?

**Comment by bluss** [comment]
The comment in issue 37 is about something else, doesn't look related.

**Comment by sanmai-NL** [comment]
It seems you see a challenge, whereas I do not. I’ll start to simply describe a positive example, followed by a small comment, maybe you can point out any issues I do not see yet.

```
StableGraph { 
    Ty: Undirected, 
    node_count: 1, 
    edge_count: 0, 
    node weights: {0: Weight { time: "2018-01-25T16:48:27.975448906+00:00", bla: 1, blo: 1 }}, 
    free_node: NodeIndex(4294967295), 
    free_edge: EdgeIndex(4294967295)
}
```
==
```
StableGraph { 
    Ty: Undirected, 
    node_count: 1, 
    edge_count: 0, 
    node weights: {0: Weight { time: "2018-01-25T16:48:27.975448906+00:00", bla: 1, blo: 1 }}, 
    free_node: NodeIndex(4294967295), 
    free_edge: EdgeIndex(4294967295)
}
```

Possibly, you could ignore `free_node` and `free_edge`.

I saw a relationship in your comment in that you are concerned with how reasonable the `PartialEq` trait is and how adding it as a trait bound at one place would have a cascading effect. Otherwise, it is unrelated indeed.

**Comment by bluss** [comment]
Yes I don't want to start off with why it's not implemented, I want to know what your perspective is on how two graphs can be equal.

**Comment by bluss** [comment]
A graph with one node is trivial, it's just like a single object itself (without the graph).

**Comment by sanmai-NL** [comment]
Does that mean you see a problem as the number of nodes rises?

A context where comparing trivial graphs is useful, is in unit tests. That is my application for such a feature.

**Comment by bluss** [comment]
One candidate for graph equivalence is graph isomorphism, but that is very expensive to compute, so it's not a good candidate for the `==` operator.

A graph is not a sequence. It does not have a start and an end. How do we line things up to compare them, finding the corresponding entires? Without a suggested algorithm, this is going nowhere. Please reopen the issue with a clear formulation of what it means for you for two graphs to be equivalent.

**Comment by sanmai-NL** [comment]
@bluss: to me, the feature request under discussion is actually much simpler than what you’re thinking of. My feature request doesn’t try to adopt any domain-specific concept of equivalence, e.g. from graph theory. All I want to know to whether one graph value matches another bit-for-bit, as works in my example. An algorithm isn’t needed, just a handful of `derive(PartialEq)` attributes. I've implemented that in a PR in the making; nothing broke. People who want to do special equivalence can still use a newtype.

**Comment by bluss** [comment]
I really don't share that perspective — any function that implements `PartialEq::eq` is an algorithm. You have come closer to describing the algorithm that you would use to define equivalence, and that's a good start.

**Comment by sanmai-NL** [comment]
Okay. What further details would you still like to see?

**Comment by mitchmindtree** [comment]
In case anyone else comes across this, this is what I've been using for `Graph` partial equality:

```rust
fn graph_eq<N, E, Ty, Ix>(
    a: &petgraph::Graph<N, E, Ty, Ix>,
    b: &petgraph::Graph<N, E, Ty, Ix>,
) -> bool
where
    N: PartialEq,
    E: PartialEq,
    Ty: petgraph::EdgeType,
    Ix: petgraph::graph::IndexType + PartialEq,
{
    let a_ns = a.raw_nodes().iter().map(|n| &n.weight);
    let b_ns = b.raw_nodes().iter().map(|n| &n.weight);
    let a_es = a.raw_edges().iter().map(|e| (e.source(), e.target(), &e.weight));
    let b_es = b.raw_edges().iter().map(|e| (e.source(), e.target(), &e.weight));
    a_ns.eq(b_ns) && a_es.eq(b_es)
}
```

I commonly come across the need for this in tests where the graph I'm generating to solve some problem needs to be compared to some expected result. That is, the need to assert that the raw_nodes and raw_edges between the two graphs are identical. That said, I can see where @bluss is coming from with this not being a clear-cut case, for example, the ordering of the nodes laid out in memory may not be important to some users.
