### ISSUE TITLE
Copy trait restriction on GraphMap nodes

### ISSUE THREAD

**Issue by jasonwhite** [bluss/petgraph#201]
### Summary

`GraphMap` requires its nodes to have the `Copy` trait (via `NodeTrait`). This forces non-trivial node types to be references instead (basically anything besides integers).

### Motivation

It would be very convenient if `GraphMap` was able to own its nodes. If this were possible, a graph could be built while iterating through an `IntoIterator`, for example.

If two duplicate nodes are to be added to the graph, both must still be held in memory because Rust doesn't know which one is actually referenced.

### Details

As far as I can tell, the reason for this restriction is because the `ordermap` crate changes ordering upon removal (i.e., with [`OrderMap::swap_remove`](https://docs.rs/ordermap/0.4.0/ordermap/map/struct.OrderMap.html#method.swap_remove)). This then forces the node type to be copied to multiple places in the `GraphMap` data structure:
https://github.com/bluss/petgraph/blob/90df37cd10895e34bb2d0f9818ece87fd6dbe771/src/graphmap.rs#L74-L78

Otherwise, if ordering was preserved even upon removal, the structure could look like this:
```rust
pub struct GraphMap<N, E, Ty> {
    nodes: OrderMap<N, Vec<(usize, CompactDirection)>>,
    edges: OrderMap<(usize, usize), E>,
    ty: PhantomData<Ty>,
}
```
...where `usize` is an index into `nodes`. Since `swap_remove` doesn't preserve ordering, the index is invalidated upon node removals.

There is a PR (https://github.com/bluss/ordermap/pull/12) that seems to have died that implemented tombstones, which would preserve ordering upon removal, enabling this issue to be fixed.

Am I missing anything else or is this the crux of the problem?

I'd be happy to help solve this with some direction. My only alternative is to implement my own simplified version of `GraphMap` where nodes are not removed, only added (since I don't need removals).

Thanks in advance!

**Comment by bluss** [comment]
The plan is to rewrite GraphMap yes. Your analysis looks fine, although I don't agree with it in the sense that: that's not the original reason it ended up being implemented this way. It was implemented with a regular HashMap first.

**Comment by jasonwhite** [comment]
I see. Thanks for the additional info. I'll close this and make a new issue.

I'm just about done with my simplified index-based `GraphMap`. You're right that it requires a rewrite. It ripples through, causing a lot of breaking changes to the API that I didn't realize at first.

Maybe a good name for the new graph type would be `StableGraphMap`? It would be like `StableGraph`, but not allow duplicate nodes.

P.S. `OrderMap` is the perfect data structure for implementing graphs. Great job on that. :+1:

**Comment by bluss** [comment]
Breaking changes would be good -- the point is to provide better features in the GraphMap. Your idea about ownership for the node weights is something I absolutely agree with.
