### ISSUE TITLE
implement IntoNeighborsDirected for EdgeFiltered

### ISSUE THREAD

**Issue by farnoy** [bluss/petgraph#202]
### Summary

Is it possible to implement IntoNeighborsDirected for EdgeFiltered? Right now it does not seem to be implemented.

### Motivation

I wanted to use a `DfsPostOrder(Reversed(EdgeFiltered))` stack. One workaround, which I think does the same and compiles, is to use `DfsPostOrder(EdgeFiltered(Reversed))`. This is because Reversed requires IntoNeighborsDirected for EdgeFiltered, which is not provided. Is there a reason the first variant cannot work?

**EDIT:**
Actually the 2nd variant can't be used either, but for a different reason - IntoNeighbors is not implemented for Reversed.

### Details

* What code needs to change? New traits? Which modules?

    I would guess, in `petgraph::visit::filter`:
    ```
    impl<'a, G, F> IntoNeighborsDirected for &'a EdgeFiltered<G, F> where ... { ... }
    ```

* Is this a new graph algorithm? Include links to papers, Wikipedia, or other
  implementations of this algorithm that exist.

    Nothing new as far as I'm aware

* Are you willing to implement this yourself? Mentor someone else and help them
  implement it?

   I could try implementing, but I'm kind of lost navigating all the instances, probably not ready to contribute

**Comment by farnoy** [comment]
As a workaround, I used `filter_map` to create a temporary graph with edges filtered the way I want. Indexes seem to be stable so it might just work. I use Arcs inside for everything so destructors of the temp graph should not be a problem for me.

**Comment by bluss** [comment]
I think it's possible nowadays, now that IntoEdgesDirected has been added. Your requested improvement here was left out due to not having time to do it all at once
