### ISSUE TITLE
Question: is_isomorphic/is_isomorphic_matching with RDF graphs?

### ISSUE THREAD

**Issue by Aaronepower** [bluss/petgraph#203]
Hello, I was wondering if `algo::{is_isomorphic, is_isomorphic_matching}` would work with RDF graphs?

**Comment by fitzgen** [comment]
Hi! I am not particularly familiar with RDF graphs, nor with the `is_isomorphic[_matching]` implementations, however:

In both the `algo::is_isomorphic` and `algo::is_isomorphic_matching` docs:

> The graphs should not be multigraphs.

From https://en.wikipedia.org/wiki/Resource_Description_Framework :

> A collection of RDF statements intrinsically represents a labeled, directed multi-graph.

That seems to me like the answer is "no".
