### ISSUE TITLE
Support reverse DFS searches

### ISSUE THREAD

**Issue by Manishearth** [bluss/petgraph#220]
### Summary

Support the ability to do a DFS search that goes _against_ the direction of the edges

### Motivation

The motivating example here is the WebAudio processing graph I'm implementing in https://github.com/servo/media . It's a DAG with audio going from sources, through multiple processing nodes, to a single audio sink. I would like to represent the graph as a StableGraph with edges going in the direction of sound since that's more in line with the general mental model of dealing with this and it's harder to be confused about what you mean by input/output incoming/outgoing.

However, to process these nodes, I have to process them dependency-wise, starting at the source nodes and working my way up.

Such a "bottom up" traversal is just a DFS post order search. Great, this library has one!

Except the DFS post order starts at a node and follows _outgoing_ edges to find "children", whereas in this case I need the opposite -- I need incoming nodes to find dependencies.

This doesn't feel like an uncommon use case. In general, most of what the graph does seems independent of the direction you choose for your edges, with all the important APIs having a `Direction` argument, so it feels weird that the search cannot be done this way.

This isn't prohibitive -- I've currently implemented the graph with the edges following dependency relationships, but writing complex code around this just gets confusing since input/output are easily mixed up.

### Details

* `DFSPostOrder` and friends would have a `Direction` argument

* Probably don't have time to implement this myself, but can help someone wanting to implement

**Comment by TeXitoi** [comment]
What about using the ReverseGraph adaptor?

**Comment by Manishearth** [comment]
Oh, `Reversed`? Hmm, this can work. I hadn't realized it was a thing.
