### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by kpcyrd** [bluss/petgraph#225]
Hey!

we're considering packaging petgraph in debian, but it seems both the ordermap and quickcheck dependencies are out of date. It seems the quickcheck dependency can be bumped without any source changes, the ordermap update requires some changes but I'm it seems I'm not familiar enough with it to provide a patch.

Thanks!

**Comment by bluss** [comment]
it will be fixed when the new version is actually released. Change has been merged.
