### ISSUE TITLE
Implement contraction hierarchies

### ISSUE THREAD

**Issue by dabreegster** [bluss/petgraph#252]
Contraction hierarchies, multi-level Dijkstra, hub labeling, etc -- these are algorithms that preprocess a large graph offline, then perform graph search online orders of magnitude faster than other approaches. I'm offering a bounty for anybody who implements this -- see https://www.reddit.com/r/rust/comments/bup78s/paid_commission_for_contraction_hierarchies_in/ for details.

**Comment by PayasR** [comment]
Lolwut? I just did it for my project.

**Comment by dabreegster** [comment]
Oh yeah? Is the implementation available somewhere?

Closing this issue, because easbar actually wrote an implementation: https://github.com/easbar/fast_paths

**Comment by PayasR** [comment]
I have an implementation that we use for our experiments, but it's not public, so sorry about that. I'll let you know if something changes though. I'll look through fast_paths as well. There are _really few_ resources on path planning for rust.
