### ISSUE TITLE
Add a versatile dfs visitor

### ISSUE THREAD

**Issue by bluss** [bluss/petgraph#37]
See also http://www.boost.org/doc/libs/1_59_0/libs/graph/doc/depth_first_search.html

```
DFS(G)                                      -                                     
  for each vertex u in V                    -                                 
    color[u] := WHITE                       initialize vertex u               
    p[u] = u                                -                                 
  end for                                   -                                 
  time := 0                                 -                                 
  if there is a starting vertex s           -                                 
    call DFS-VISIT(G, s)                    start vertex s                    
  for each vertex u in V                    -                                 
    if color[u] = WHITE                     -                                 
      call DFS-VISIT(G, u)                  start vertex u                    
  end for                                   -                                 
  return (p,d_time,f_time)                  -                                 
                                            -                                 
DFS-VISIT(G, u)                             -                                 
  color[u] := GRAY                          discover vertex u                 
  d_time[u] := time := time + 1             -                                 
  for each v in Adj[u]                      examine edge (u,v)                
    if (color[v] = WHITE)                   -                                 
      p[v] = u                              (u,v) is a tree edge              
      call DFS-VISIT(G, v)                  -                                 
    else if (color[v] = GRAY)               -                                 
      ...                                   (u,v) is a back edge              
    else if (color[v] = BLACK)              -                                 
      ...                                   (u,v) is a cross or forward edge  
    ...                                     -                                 
  end for                                   finish edge (u,v)                 
  color[u] := BLACK                         -                                 
  f_time[u] := time := time + 1             finish vertex u                   

```

**Comment by BurntPizza** [comment]
Could you elaborate on what's wanted here?

**Comment by bluss** [comment]
Good question, I haven't really dug into this. For example the kosaraju implementation in petgraph needs to use finishing times (`petgraph::algo::scc`) so it would really use the "finish vertex" event of the dfs visitor scheme above. (I don't think scc is in dire need of this improvement.)

I haven't thought about if you'd use a visitor trait or how the thing would be expressed in Rust. In the spirit of boost it should avoid doing anything for the events that don't have a handler.

**Comment by BurntPizza** [comment]
I think one thing that will likely (or certainly) block this (and is needed to generalize various `petgraph::algo`s) is a `visit` trait (or some other mechanism) for looking at the actual nodes (i.e. including weights) of a generalized graph (`GraphBase`/`GraphRef``), as there is currently no way to get anything other than the `G::NodeId`s. Not even a way to then use the ids to index into the graph. Currently this does exist for edges via `IntoGraphEdges` and friends.

**Comment by bluss** [comment]
if `impl Trait` is stabilized, all the iterator visit traits can be redesigned again. Then we can finally (I think?) have graph visitor traits and mutate the graph, which is impossible today.

**Comment by bluss** [comment]
If there's a visit trait missing, a specific issue for it is wanted.

**Comment by BurntPizza** [comment]
Right, I just don't know how you might want to do it.
Could directly have a `IntoNodeReferences` (and support structure like `IntoEdgeReferences`, but could also modify `GraphBase` to allow some way to go from a `G::NodeId` to a `NodeRef` similar to `EdgeRef`.

**Comment by bluss** [comment]
It's natural that we add many small traits with very minor roles (GraphBase) until we know better how we should factor the functionality into logical traits. I don't foresee adding anything to GraphBase at this time, it's only carrying those associated types. More capabilities are added in other traits.

**Comment by bluss** [comment]
New dfs visitor in #87. Maybe there's a nice way to generalize it, or factor out the common parts of Dfs and DfsPostOrder.

For example, Dfs only needs one bit per node (discovered / mark gray), DfsPostOrder two bits per node (discovered / gray vs finished / black).

**Comment by bluss** [comment]
Adding `PartialEq` to `NodeId` is reasonable, but I don't like all the places where the new trait bound is required (`Dfs` and so on, if you try it).

**Comment by bluss** [comment]
Approachable overview http://eli.thegreenplace.net/2015/directed-graph-traversal-orderings-and-applications-to-data-flow-analysis/

**Comment by bluss** [comment]
Recursive full dfs visitor added in #97. What remains is maybe an iterative version of equal power.

**Comment by bluss** [comment]
A lot of your suggestions are now reality in 0.4.0 (DataMap trait, NodeId requires PartialEq and so on).

**Comment by BurntPizza** [comment]
Glad I could contribute to the design.
Time to update my dependencies again!

**Comment by bluss** [comment]
Oh and there's no consuming iterators yet, but the `Element` enum and related iterator things are on the road to be there.
