### ISSUE TITLE
`to_graph` method for `GraphMap`s?

### ISSUE THREAD

**Issue by marcusklaas** [bluss/petgraph#66]
`GraphMap`s are nice because they are generally easier to construct than `Graph`s. Unfortunately, most algorithms work only on `Graph` objects. Would it make sense to add a method to easily create an equivalent `Graph` to `GraphMap`? Then one could have the best of both worlds: easy graph construction using `GraphMap::from_edges`, and access to the full range of algo's!

**Comment by marcusklaas** [comment]
Oh, and of course thanks for making/ maintaining this library! It is pretty dope.

**Comment by bluss** [comment]
Great! :smile:

Ok, that's an interesting idea that didn't cross my mind.

Please look at this GraphBuilder struct https://github.com/bluss/petulant-avenger-graphlibrary/blob/builder/src/builder.rs  (that's on a temporary branch).

So the question is, is a dedicated GraphBuilder thing better? Can GraphMap do both duties?

**Comment by bluss** [comment]
I've also of course implemented a directed GraphMap on some branch. Maybe GraphMap is enough with that, then it could build directed graphs too.
