### ISSUE TITLE
Tracking dijkstra

### ISSUE THREAD

**Issue by diwic** [bluss/petgraph#69]
Hi!

For a small project of mine I was using algo::dijkstra, but I needed to track the nodes and/or edges visited between source and destination. With the Copy restriction of K, that was quite hard to do, so I did a quick-n-dirty hack of reducing K to clone and adding "clone" everywhere the compiler complained.

I can submit that hack as a PR if you like, but perhaps there is some solution that performs better?

**Comment by bluss** [comment]
Using Clone instead of Copy should not be a problem. I don't immediately understand how the node tracking works though. You'd have to rely on implementation details of the algorithm?

**Comment by diwic** [comment]
Well, here's what I used as my `K`:

    #[derive(Debug, Clone, Default)]
    struct TrEdge(f64, HashSet<String>); 

I then implemented
  *  `Add` for `TrEdge` as `TrEdge(self.0 + rhs.0, self.1.union(rhs.1))`, 
  * `PartialOrd` for `TrEdge` as just comparing the `self.0.partial_ord(rhs.0)` 
  * The closure mapped `graph.edges` into `TrEdge`s like this: `|graph, nn| graph.edges(nn).map(|(a, &b)| (a, TrEdge::new(&graph[a], b))`.

...it seemed to work fine and give correct results on the things I checked, once I had changed `Copy` to `Clone` on `K` - but maybe I'm doing something wrong?

**Comment by bluss** [comment]
It may work fine but I wouldn't recommend it. Seems to be relying on implementation details in how the algorithm uses `+`.

**Comment by diwic** [comment]
I'm afraid I don't understand - could the `+` be used for anything else than adding two distances, or could adding two distances ever mean something else than taking a union of the set of visited nodes?

**Comment by bluss** [comment]
It's using the operations far outside the reasonable implicit protocol in the Add trait IMO. The dijkstra function is a bit fast and loose, using `Default` instead of "zero" unfortunately, but that's another thing that can be fixed with docs.

I think it's completely fine to copy the code and produce a more flexible implementation that fits your use case. If it ends up being flexible and general it is very welcome back as a PR too.
