### ISSUE TITLE
Can I use with an huge graph structure?

### ISSUE THREAD

**Issue by LeMoussel** [bluss/petgraph#75]
I'm developing an application in which I need a structure to represent a huge graph between 1 000 000 and 6 000 000 nodes and 10 or 300 edges from each node. The nodes representation will contain some attributes. 

Can I use petgraph to do it? What is petgraph limits? memory use ?

**Comment by bluss** [comment]
Memory will be limiting as well as algorithmic issues. 300 edges per node might already be slow depending on what you want to do, but since that's still a sparse graph I think petgraph should manage it.
