### ISSUE TITLE
Lift the tarjan scc algorithm from tests into petgraph::algo

### ISSUE THREAD

**Issue by bluss** [bluss/petgraph#79]
It needs to be generalized and then it's good to go

**Comment by BurntPizza** [comment]
Do you want it to replace the current `scc`? Or have it as something like `tarjan_scc`?

**Comment by bluss** [comment]
I'm thinking we want both

**Comment by stjepang** [comment]
Why do you want both?
Btw, tarjan_scc can be made iterative instead of recursive (it's just a DFS after all).

**Comment by bluss** [comment]
Not sure. They do have different general requirements, not sure how much they can be harmonized. Tarjan is generally smarter since it doesn't require incoming edges queries. Kosaraju's one doesn't require NodeIndexable, so it's the one that supports GraphMap.

**Comment by bluss** [comment]
(Kosaraju's algo uses Dfs with reversed edges)
